language: node_js

node_js:
  - '10'

install:
  - npm install

script:
  - npm run test:ci
  - codecov

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?/
